### PR TITLE
Update nav.html - border adjust

### PR DESCRIPTION
**Pull request by RodrigoWebDev**
removed border-left of the ul, and added the same border on the li child, keeping a pattern between the other borders

### CODE REVIEW

**Comment by CrazyBtchPhyscoMom33** [comment]
Nice

**Comment by MikeMcQuaid** [comment]
> removed border-left of the ul, and added the same border on the li child, keeping a pattern between the other borders

@RodrigoWebDev What's the advantage of this change? It looks the same to me. Thanks!

**Comment by stestiffy88** [comment]
title: Open Source Guides
description: Learn how to launch and grow your project.

**Comment by PrachiChi** [comment]
<br>

**Pull request closed without merging**
