### PR TITLE
Translation: Chinese (China)

### PR DESCRIPTION
**Pull request by lijiangsheng1**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/gh-pages/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by nayafia** [comment]
@bkeepers for you

**Comment by ekosutopo** [comment]
'Reslove'

**Comment by lijiangsheng1** [comment]
Hi, 
   What I will do next can pass and merge to trunk？anyone help me?
Thanks very much.

**Comment by MikeMcQuaid** [comment]
@lijiangsheng1 I've merged the first translation to this repository (Spanish) and updated the documentation on the latest translations approach (https://github.com/github/opensource.guide/blob/gh-pages/docs/translations.md). Please commit fixes so `./script/test` passes and merge conflicts are resolved and I'll get it merged in ASAP. Thanks!

**Comment by MikeMcQuaid** [comment]
@lijiangsheng1 I've updated your branch based on the latest translations approach (https://github.com/github/opensource.guide/blob/gh-pages/docs/translations.md). Please fix all the `linking to internal hash` CI failures (you can run `./script/test` to reproduce) and I'll merge this in. Thanks again!

**Comment by MikeMcQuaid** [comment]
@lijiangsheng1 Instead of changing the link names to be English look at the generated HTML in `_site` and use the correct anchors there. For example, see https://github.com/github/opensource.guide/pull/514/commits/6e500de29538e31063e9674f699f8b36423148f1

**Comment by MikeMcQuaid** [comment]
I fixed up these changes. Thanks again @lijiangsheng1 for all your work!

**Comment by MikeMcQuaid** [comment]
@lijiangsheng1 Now that https://github.com/github/opensource.guide/pull/779 is merged it should be easier to fix the headers and links. Any chance you could do that?

**Pull request merged**
