### PR TITLE
Use @primer/sync to sync Primer CSS sources to git

### PR DESCRIPTION
**Pull request by shawnbot**
This removes `node_modules` from git and uses our new [primer-sync](/primer/sync) tool to copy npm-installed Primer CSS source files (`primer*/**/*.scss`) to `_sass/`, then adds that directory to `sass.include_paths` in the Jekyll config.

This saves over 3MB in git (`node_modules` was 3.1MB before installing `@primer/sync`, and `_sass` weighs in at a svelte 860K)! 🎉

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@shawnbot Will hold off merging https://github.com/github/opensource.guide/pull/821 to avoid merge conflicts here.

> This removes `node_modules` from git and uses our new [primer-sync](/primer/sync) tool to copy npm-installed Primer CSS source files (`primer*/**/*.scss`) to `_sass/`, then adds that directory to `sass.include_paths` in the Jekyll config.

How/when is this tool run? My concern is that this will interfere with the dependant workflow (e.g. https://github.com/github/opensource.guide/pull/821).

If there's manual steps that need to be added to get this tool run: would it be possible to add CI checks to ensure that it's been run correctly?

Thanks!

**Comment by MikeMcQuaid** [comment]
@shawnbot I haven't dug into how they work but as long as that was done before a PR was merged (and before this PR is merged) that could work!

**Comment by MikeMcQuaid** [comment]
@shawnbot Sorry, I'm not sure what to suggest except the other PR.

**Comment by ahmad380360** [comment]
تشغيل الاده بدايه التشغيل الغعلي

**Pull request closed without merging**
