### PR TITLE
update for more readability

### PR DESCRIPTION
**Pull request by ciminbinazadeh**
Hi
changed for more readability
Good time :)

- [ ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@ciminbinazadeh one issue that needs fixed here: https://github.com/github/opensource.guide/runs/4065975575?check_suite_focus=true#step:7:69

**Comment by ciminbinazadeh** [comment]
> @ciminbinazadeh one issue that needs fixed here: https://github.com/github/opensource.guide/runs/4065975575?check_suite_focus=true#step:7:69

thank you
Edited 🙂

**Comment by Twins206** [comment]
Basically my. Console
So far won't update soff where.any app Pl


Hey my console not up to date

**Comment by zahirpatel110** [comment]
Done

**Review by MikeMcQuaid — APPROVED** [review]
Thanks again @ciminbinazadeh!

**Review by Bobah8716 — COMMENTED** [review]
😀

**Review by MaryJaneLove4 — COMMENTED** [review]
👍

**Pull request merged**
