### PR TITLE
Fix turkish translations

### PR DESCRIPTION
**Pull request by onurravli**
- [X] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by Andarina** [comment]
#3303 bump_the_dependency_with_2_this
#2 add _link_edit_content
#3117 Git_commit

**Review by jmeridth — APPROVED** [review]

**Review by jmeridth — APPROVED** [review]

**Review by jmeridth — DISMISSED** [review]
Thank you for your contribution and getting these sections updated.

**Comment by Shubhf** [comment]
Hey @onurravli Can I still contribute to this issue?

**Comment by E-456-sya** [comment]
- [ ]

**Pull request merged**
