### PR TITLE
Create tr.yml

### PR DESCRIPTION
**Pull request by ali-demirtas**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?
- [x] Have you enabled GitHub Pages Previews by pressing <keyboard>`Enable GitHub Pages`</keyboard> on the right sidebar to trigger a pages build for this PR?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by kenyonj** [comment]
Please explain the addition of the theme in the jekyll config. Or, if this is just for the Turkish translation, can you remove that change from this PR?

Thanks for your contribution!

**Comment by koyemanaung** [comment]
support and issue

**Comment by rodolfojr15** [comment]
hello i qant to fixx all

**Comment by mlinksva** [comment]
Closing in preference to completed Turkish translation in #1112. @ali-demirtas or others watching this issue if you'd like to take a look at #1112 please do!

**Pull request closed without merging**
