### PR TITLE
fix: Correct typos and spacing in Korean documentation (metrics page)

### PR DESCRIPTION
**Pull request by hwahyeon**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----
Hello,

I have made updates to the Korean documentation (/ko/metrics.md) to correct spacing and typos. These changes enhance the readability and accuracy of the document.

#### Changes:
- Fixed improper spacing between words and sentences.
- Corrected typos.
  - (사디 → 다시)
  - (이동하보십시오. → 이동해 보십시오.)

Please review the changes and let me know if any further adjustments are needed.

Thank you!

### CODE REVIEW

**Review by Betbenim — COMMENTED** [review]
Fin

**Review by Betbenim — COMMENTED** [review]
Goo

**Comment by nickloo8888** [comment]
Closed my pr ....for what matters to me.have you pay workmanship for me... hiaaaa can't see the notifications.. and you think me can understand your Korea language...

**Comment by Yeonheekang** [comment]
#3223

**Review by ahpook — APPROVED** [review]
Thank you for these fixes! 당신의 일에 감사드립니다

**Pull request merged**
