### PR TITLE
fix: code scanning alerts re: workflows permissions

### PR DESCRIPTION
**Pull request by jmeridth**
- [x] add permissions to stale workflow
- [x] add permissions to tests workflow
- [x] remove empty brackets on pull_request branch in tests workflow
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by A1811-qbite** [comment]
🤔

**Comment by Farahnady** [comment]
Fahimeh

**Review by zkoppert — APPROVED** [review]

**Review by Jhonsshons — COMMENTED** [review]
Wh

**Comment by jmeridth** [comment]
@github/communities-oss-reviewers bump 😄

**Review by ahpook — APPROVED** [review]
lgtm!

**Pull request merged**
