### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Tatsuru-Kikuchi**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by gsayr481** [comment]
The changes help update info and make everything so much easier

**Comment by maisoenaingtun** [comment]
{{/ Update index.html #2266}}

**Review by tuanggolt — APPROVED** [review]

**Comment by tuanggolt** [comment]
Tuanggo

**Comment by tuanggolt** [comment]
#9 maxte

**Pull request closed without merging**
