### PR TITLE
Removes node_modules and adds it to the ignore list

### LINKED ISSUE #793: node_modules not on .gitignore
I've faced this when working on  #715 . I've checked out the [master's .gitignore](https://github.com/github/opensource.guide/blob/master/.gitignore) and it also doesn't list node_modules. Is there any reason behind that? I mean, my branch right now is tracking every change on npm packages, and I'm wondering if this is the desired result and why.

### PR DESCRIPTION
**Pull request by leolleocomp**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

Removes `node_modules` directory from version control. Closes  #793

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Ideally this would have failed CI 🤔.

**Comment by MikeMcQuaid** [comment]
@kenyonj any idea from https://travis-ci.org/github/opensource.guide/builds/473920425?utm_source=github_status&utm_medium=notification why this didn't?

**Comment by kenyonj** [comment]
> @kenyonj any idea from https://travis-ci.org/github/opensource.guide/builds/473920425?utm_source=github_status&utm_medium=notification why this didn't?

CI didn't fail and that was the only required status check before allowing the merge. I just turned on `github/pages` as another required check, which would have prevented this.

**Comment by shiftkey** [comment]
@MikeMcQuaid @kenyonj apologies for not catching this after the merge

**Comment by MikeMcQuaid** [comment]
@shiftkey No worries!

**Pull request merged**
