### PR TITLE
chore: fix typo

### PR DESCRIPTION
**Pull request by webfansplz**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

Fix typo: `IOS` => `iOS`

-----

### CODE REVIEW

**Comment by VardaQuraishi** [comment]
Can I work on this typo issue @webfansplz  @bruce  @mtodd @spicycode @tpope ?

**Comment by ahpook** [comment]
Do not tag people like this, @webfansplz, it is spam and violates [the Acceptable Use Policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-disrupting-the-experience-of-other-users).

**Comment by ahpook** [comment]
I misread the thread, it was not @webfansplz who did the spam-tag.

**Review by ahpook — APPROVED** [review]
LGTM

**Pull request merged**
