### PR TITLE
Translation: Korean

### PR DESCRIPTION
**Pull request by minwook-shin**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/gh-pages/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

Translation: Korean #451 

Added Korean translation

cname : ko.opensource.guide

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@minwook-shin I've updated your branch based on the latest translations approach (https://github.com/github/opensource.guide/blob/gh-pages/docs/translations.md). Please fix all the `linking to internal hash` CI failures (you can run `./script/test` to reproduce) and I'll merge this in. Thanks again!

**Comment by MikeMcQuaid** [comment]
@minwook-shin Instead of changing the link names to be English look at the generated HTML in `_site` and use the correct anchors there. For example, see https://github.com/github/opensource.guide/pull/514/commits/6e500de29538e31063e9674f699f8b36423148f1

**Comment by minwook-shin** [comment]
Thank you for answer. @MikeMcQuaid. I know this commit... but, if the non-alphabetic characters are on the link, encoding is corrupted and an error occurs.

**Comment by minwook-shin** [comment]
non-alpha-error-ex
this is example picture.

**Comment by minwook-shin** [comment]
(Whatever the way) I removed all the errors! :)

**Comment by MikeMcQuaid** [comment]
@minwook-shin Ok, that's a shame but glad to have this working anyway. 
Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
