### PR TITLE
Edit for more readability

### PR DESCRIPTION
**Pull request by ciminbinazadeh**
Hi
Edit for more readability.
Good luck

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by ciminbinazadeh** [comment]
Please help me for This error "Process completed with exit code 1."

**Review by Amoon79 — COMMENTED** [review]
Can't understand scriptures,, not one correct sentence

**Comment by nholden** [comment]
> Please help me for This error "Process completed with exit code 1."

👋 Hi, @ciminbinazadeh! I see this annotation on the files changed tab. I think addressing it could get the tests passing.

Screen Shot 2021-11-16 at 2 12 26 PM

**Comment by ciminbinazadeh** [comment]
> I see this annotation on the files changed tab. I think addressing it could get the tests passing.
Hi @nholden 
thank you 🙏🌸

**Comment by Amoon79** [comment]
Thanks to nick and his amazing magic work ,, glad u have it done

**Review by nholden — APPROVED** [review]
Thanks for this contribution! 💖

**Pull request merged**
