### PR TITLE
add vietnamese language into locales folder

### PR DESCRIPTION
**Pull request by cbleduytan**
- Hi, I'm Tan (Niu), I'm from Vietnam. I just added a new language by Vietnamese. Please, can anyone review through my first task and merge it for me?

### CODE REVIEW

**Comment by ahpook** [comment]
Thank you for working on this! It will be good to have a Vietnamese translation.

However, it will not work without a matching `_articles/vn` directory though. Can you please add that directory with a copy of all the articles, even if they are not translated yet? This is steps 5, 6 and 7 in the docs https://github.com/github/opensource.guide/blob/main/docs/translations.md#starting-a-translation

Thanks!

**Review by ahpook — CHANGES_REQUESTED** [review]
This is a good first step but it also needs a language directory for the site to work, see my comment for more details.

**Comment by Avalir1996** [comment]
http://hk-mbx03.mioffice.cn/

**Review by gavatron90 — COMMENTED** [review]
_data/locales/vn.yml

**Comment by ahpook** [comment]
I'm going to close this for inactivity, if someone wants to pick it up and carry forward with some translations that'd be awesome.

**Pull request closed without merging**
