### PR TITLE
[translation] missing titles translated for PL

### PR DESCRIPTION
**Pull request by olsza**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----
1) The main title has been translated - in addition, they will make it easier to search in search engines (SEO), if someone enters this phrase in Polish.
2) Forgot to translate the title of one chapter - I did it now :)
3) The word "friends" was translated in the footer
4)  in nav given the mother tongue "Polski" (in Poland "Polish" is "Polski", that is, in Polish) [I deposited the same in PR #1910 (my duplicate)]

### CODE REVIEW

**Comment by olsza** [comment]
Hi @mlinksva, because I can see that you translated this project into Polish, or maybe how to do something quick CR of this PR and the other 2, i.e. #1916 and #1910
thanks in advance

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @olsza!

**Comment by olsza** [comment]
> Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @olsza!

I must admit that the guide helped and motivated me a lot :) so I also started to help, I started helping early in another project - also in translation ... project https://github.com/Laravel-Lang/lang

**Comment by MikeMcQuaid** [comment]
Aw, that makes me very happy to hear 😍

**Pull request merged**
