### PR TITLE
Fix: French typos

### PR DESCRIPTION
**Pull request by omahs**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by Mohamad1112we** [comment]
P

**Comment by Astormalo** [comment]
[](url)

**Comment by sammiie** [comment]
To provide a fix for French typos, you would typically need access to the codebase and permission to make changes. Here's a general outline of how you can fix French typos in a GitHub repository:

Clone the Repository:
If you haven't already, clone the repository to your local development environment. Use the git clone command followed by the repository URL.
git clone https://github.com/username/repository.git
Create a Branch:
Create a new branch for your changes. This helps isolate your work from the main branch (often called master or main).

bash
git checkout -b fix-french-typos
Locate and Fix Typos:
Navigate to the files where the French typos are located. Review the code or documentation carefully to identify and correct the typos.

Commit Your Changes:
Once you've made the necessary corrections, commit your changes with a clear and concise commit message that describes what you've fixed.

bash
git add .  # Stage your changes
git commit -m "Fix French typos in code and documentation"
Push Your Branch:
Push your branch with the fixes to the remote repository on GitHub.

bash
git push origin fix-french-typos
Create a Pull Request (PR):
Visit the GitHub repository in your web browser and navigate to the "Pull Requests" section. Click on "New Pull Request" and select your branch as the source for the PR. Provide a description of the changes you've made.

Review and Merge:
Wait for reviewers to check your changes and, if they approve, merge your PR into the main branch.

Cleanup:
After your PR is merged, you can delete your feature branch locally and on GitHub.

bash
# Locally
git checkout main  # Switch back to the main branch
git branch -d fix-french-typos  # Delete the feature branch

# On GitHub
Delete the branch through the GitHub interface.
By following these steps, you can contribute to fixing the French typos in the repository. Remember to adhere to the project's coding guidelines and contribute positively to the open-source community.

**Review by ahpook — APPROVED** [review]
Merci beaucoup!

**Comment by ahpook** [comment]
Getting a test failure:
```
- _site/fr/building-community/index.html
  *  linking to internal hash #ne-tolèrez-pas-les-mauvais-acteurs that does not exist (line 570)
     <a href="../building-community/#ne-tolèrez-pas-les-mauvais-acteurs">agissez immédiatement</a>
```

**Comment by omahs** [comment]
@ahpook I just changed the anchor link

**Review by underwoo16 — APPROVED** [review]

**Pull request merged**
