### PR TITLE
improve

### PR DESCRIPTION
**Pull request by lovedworking**
which way to go

- [ ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by alsayedzomrawi** [comment]
[My Collection of Writings.docx](https://github.com/github/opensource.guide/files/7192395/My.Collection.of.Writings.docx)

**Comment by alsayedzomrawi** [comment]
> which way to go
> 
> * [ ]  Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
> * [ ]  Have you explained what your changes do, and why they add value to the Guides?
> 
> **Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

**Comment by mohammadradzih** [comment]
gh pr checkout 2546

**Comment by Austinfourie** [comment]
It's just the app go in and out

**Pull request closed without merging**
