### PR TITLE
Another convert in to Urdu language

### PR DESCRIPTION
**Pull request by mishaDova**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by tomthorogood** [comment]
@mishaDova Thanks so much for creating this pull request. I'm not sure if you're aware that tests are failing because some of the links aren't translated yet. Are you planning to finish those out? I'd hate for this work to go left unmerged.

**Review by nafeef123 — COMMENTED** [review]
Good

**Comment by jmeridth** [comment]
@mishaDova @Areebey is this a redo of #3223?  If so can we please close #3223 and change the title to this one to be `Convert in to Urdu language`?  Thank you.

**Comment by jmeridth** [comment]
I just realized @mishaDova does not have any commits on this PR.  They took the commits from #3223 and @Areebey.  Closing this to allow that PR to go through if updated and give @Areebey credit for their work.

**Pull request closed without merging**
