### PR TITLE
Added a scroll to top button in the website to avoid inconvenience by viewers.

### PR DESCRIPTION
**Pull request by eshal26**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

### CODE REVIEW

**Comment by mohdamjadsk** [comment]
A

**Comment by mohdamjadsk** [comment]
Afreen

**Comment by zkoppert** [comment]
CI failure: `API rate limit exceeded for 20.172.43.146.` I will try again later.

**Review by zkoppert — APPROVED** [review]
What a great contribution @eshal26! Thanks for taking the time to get this working! 🎉

**Review by Sajadgaldi — COMMENTED** [review]
Leavd and review

**Review by Sajadgaldi — COMMENTED** [review]
Review

**Pull request merged**
