### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by tolin1420**
- [ ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by tolin1420** [comment]
[keyboard-shortcuts-windows.pdf](https://github.com/github/opensource.guide/files/7547106/keyboard-shortcuts-windows.pdf)

**Comment by tolin1420** [comment]
> [keyboard-shortcuts-windows.pdf](https://github.com/github/opensource.guide/files/7547106/keyboard-shortcuts-windows.pdf)

**Comment by mohs27** [comment]
``https://autoclaim.in/wmi/Malipor1200

**Comment by Amoon79** [comment]
I opend the link and its reading some numbers ,,14 s/h

**Pull request closed without merging**
