### PR TITLE
Create it.yml

### PR DESCRIPTION
**Pull request by albanobattistella**
- [ ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by OMSOStonie** [comment]
Do not afraid of the coming storm as long as we are surrounding with Love!

**Comment by deniseyu** [comment]
hey @albanobattistella, thanks for getting this started!

It looks like CI is failing because when a new set of languages is added, it expects all the existing pages to be copied into a new directory prefixed by the new language code. Here's what that directory looks like for the French translation, for example: https://github.com/github/opensource.guide/tree/main/_articles/fr

You don't have to submit translations for ALL those pages as part of this PR, as that's a big ask 😅 but I ask that you duplicate the existing English files over to `_articles/it/`, and then I can open a "Help Wanted" issue to get more Italian speakers to help with translating those pages!

**Review by Yodag7354 — APPROVED** [review]

**Review by Yodag7354 — APPROVED** [review]

**Comment by Limlay** [comment]
Morning

**Review by Limlay — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
@albanobattistella Any news on this? Thanks!

**Review by bungfut — CHANGES_REQUESTED** [review]
n p

**Comment by MikeMcQuaid** [comment]
Passing on this for now. Please feel free to reopen when a little further along @albanobattistella!

**Pull request closed without merging**
