### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by streghstreek**
- [ ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Review by masumh — COMMENTED** [review]
Thanks

**Comment by masumh** [comment]
Thanks

**Review by masumh — APPROVED** [review]

**Review by masumh — APPROVED** [review]

**Review by masumh — APPROVED** [review]
[GitHub Actions CI](https://github.com/github/opensource.guide/actions/workflows/tests.yml)

**Review by masumh — APPROVED** [review]
https://github.com/github/opensource.guide/pull/2375#issue-622023366

**Comment by masumh** [comment]
> * [ ]  Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
> * [ ]  Have you explained what your changes do, and why they add value to the Guides?
> 
> **Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

https://github.com/github/opensource.guide/pull/2375#issue-622023366

**Review by loida24 — COMMENTED** [review]
Nice

**Review by loida24 — COMMENTED** [review]
streghstreek thanks

**Review by loida24 — APPROVED** [review]

**Review by loida24 — COMMENTED** [review]
streghstreek:patch-1

**Pull request closed without merging**
