### PR TITLE
Fix typos and minor errors in German translation

### PR DESCRIPTION
**Pull request by asuender**
- [X] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you explained what your changes do, and why they add value to the Guides?

-----

Some sentences sounded weird, so I corrected them, as well as some other typos on all subpages.

### CODE REVIEW

**Review by rayhan97794 — COMMENTED** [review]
Nice project

**Comment by Realmebd** [comment]
fixed my Activision

**Comment by Realmebd** [comment]
minor error

**Comment by Saratobon09** [comment]
Good project!

**Comment by Sonnybones** [comment]
Great job 🫥

**Comment by Sonnybones** [comment]
Good project 🫶

**Pull request merged**
