### PR TITLE
Create SECURITY.md Touhidul islam

### PR DESCRIPTION
**Pull request by touhidislam783**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Review by Mk1206mk — COMMENTED** [review]
gh pr checkout 2935

**Comment by Mk1206mk** [comment]
gh pr checkout 2935

**Comment by Mk1206mk** [comment]
touhidislam783:touhidislam783-patch-1

**Review by jery2555 — COMMENTED** [review]
Submit add this reference number

**Review by Aexmuxomor — COMMENTED** [review]
SECURITY.md

**Comment by Maxamadsamriye** [comment]
touhidislam783:touhidislam783-patch-1

**Pull request closed without merging**
