### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Beheratapas**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Review by 8136800738 — APPROVED** [review]

**Review by soffieprincess09 — APPROVED** [review]
Duplicate of #

**Comment by Beheratapas** [comment]
Thankyou so much

**Review by thanuw — APPROVED** [review]

**Comment by meme69-sketch** [comment]
Approved

Kind Regards

**Comment by Beheratapas** [comment]
Get Outlook for Android<https://aka.ms/AAb9ysg>

**Pull request closed without merging**
