### PR TITLE
Translation `How to contribute' to Korean

### PR DESCRIPTION
**Pull request by Blinders**
Translation `How to contribute' to Korean

### CODE REVIEW

**Comment by Blinders** [comment]
Sorry, My mistake this pull request.. please cancel and close this PR

**Comment by bkeepers** [comment]
Hey, no worries. I'm glad to see there's a Korean translation in the works! 

Would you be up for opening an issue as described in the [translation docs](https://github.com/github/opensource.guide/blob/i18n/docs/translations.md#starting-a-translation) from #295 so others can track progress on it?

**Comment by Blinders** [comment]
@bkeepers Thank you for your kind comment. I will look for more and open the issue.  I'm a newbie..
while translating this project,  I am learning about contributions.

**Comment by bkeepers** [comment]
@Blinders that's great!  We're so excited to have you helping here!

If you ever have any questions, want help with anything, or just want feedback, don't hesitate to ping me.

**Pull request closed without merging**
