### PR TITLE
Improved installation steps

### PR DESCRIPTION
**Pull request by UlisesGascon**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

I added an additional step to clarify how to grant execution permissions to the scripts in order to run the project locally.

### CODE REVIEW

**Comment by UlisesGascon** [comment]
I think the errors in the CI are not related to this changes 🤔

**Review by zkoppert — APPROVED** [review]
Great additions! Thanks for contributing again!

**Comment by Maths42** [comment]
That's nice

**Review by thannawat152005 — COMMENTED** [review]
@bruce

**Comment by Milanhe92** [comment]
5aeb14ac16fb5b1a37984bd4eafe6a3a1b62a334

**Pull request merged**
