### PR TITLE
added NCoC as a sample CoC

### PR DESCRIPTION
**Pull request by lutzhorn**
Having no CoC can be a good option for many projects.

### CODE REVIEW

**Comment by lee-dohm** [comment]
Thank you for the PR. We at GitHub believe that reasonable adults that are capable of having adult discussions aren't put off by having guidelines for civil discussions documented. We also have specifically selected codes of conduct that we believe to be effective in creating environments for respectful discourse. Implying that people aren't adults is not a good way to achieve that goal.

**Comment by lutzhorn** [comment]
> Implying that people aren't adults is not a good way to achieve that goal.

I don't quite understand this. Where and by whom was this impliet?

**Comment by lee-dohm** [comment]
It was implied in your suggested text.

**Comment by lutzhorn** [comment]
What about improving the text? I am open for any suggestion that would make the PR better.

My point is that option of not having a CoC should be mentioned. How would you phrase this?

**Comment by 8-uh** [comment]
disapproval dot gif

**Comment by MikeMcQuaid** [comment]
> My point is that the option of not having a CoC should be mentioned. How would you phrase this?

We encourage all open source communities on GitHub to have a Code of Conduct.

**Pull request closed without merging**
