### PR TITLE
direction: rtl for fa translation

### PR DESCRIPTION
**Pull request by ciminbinazadeh**
hi
direction: rtl for fa translation

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by ciminbinazadeh** [comment]
hi @MikeMcQuaid 
This error ""Process completed with exit code 1."" has been coming for all changes since two days ago!
Please help me to solve it

**Comment by MikeMcQuaid** [comment]
Thanks again @ciminbinazadeh!

**Comment by ciminbinazadeh** [comment]
> Thanks again @ciminbinazadeh!

@MikeMcQuaid 
🙏🏻🙏🏻🙏🏻🙏🏻🌸

**Comment by Swansoppia** [comment]
> hi direction: rtl for fa translation
> 
> * [x]  Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
> * [x]  Have you explained what your changes do, and why they add value to the Guides?
> 
> **Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

**Review by Swansoppia — COMMENTED** [review]
assets/css/custom.scss

**Review by Swansoppia — COMMENTED** [review]
b7d8790

**Review by Swansoppia — COMMENTED** [review]
b7d8790

**Review by Swansoppia — COMMENTED** [review]
945ef88

**Comment by ciminbinazadeh** [comment]
> [945ef88](https://github.com/github/opensource.guide/commit/945ef880922cd04587cd275b00ad3e5670fe5d20)

hello @Swansoppia 
Why revert? :)

**Comment by jskeet** [comment]
@ciminbinazadeh: I've come here investigating @Swansoppia's behavior having received a couple of "contributions" myself. I suspect this is either a bot gone wrong, or spam of some description. I'll be reporting the user to GitHub to investigate.

**Comment by MikeMcQuaid** [comment]
@jskeet @ciminbinazadeh Yeh, this repository gets huge amounts of spam. They are flagged as spammy now; best to report (or, if not, ignore). Thanks and sorry ❤️

**Comment by PressureTechs** [comment]
Thank you

**Pull request merged**
