### PR TITLE
Fix Farsi Hyperlinks

### PR DESCRIPTION
**Pull request by ChristolisOfficial**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----
This pull request aims to fix some HTML-Proofer errors that are caused by a small number of outdated hyperlinks found inside the Farsi translations directory. Oddly enough, they randomly started showing up as I was working on #2791. I noticed that those hyperlinks exist in the main branch as well (and they don't work as expected on the main website) which prompted me to create this pull request.

### CODE REVIEW

**Comment by Ramindada** [comment]
#a-checklist-before-you-contribute

**Comment by Henrytech22** [comment]
Why??

**Comment by Henrytech22** [comment]
Bnb

**Comment by Henrytech22** [comment]
BNB/#+999@Henrytech2+98$/💯 2754bnB

**Comment by Henrytech22** [comment]
GoMYwALlEt99HeNBIa100999R2Y..  BnB code of my day

**Comment by Henrytech22** [comment]
Am ready to Marge with anyone from Bnb

**Comment by Henrytech22** [comment]
Go Bnb

**Comment by MaryJaneLove4** [comment]
Please, you have to explain me. I don´t understand. so sorry

so 9. 4. 2022 v 17:07 odesílatel Henrytech22 ***@***.***>
napsal:

**Comment by MikeMcQuaid** [comment]
Oh no! Missed this PR until I'd done this myself manually 🤦🏻 . Thanks anyway @ChristolisOfficial!

**Pull request closed without merging**
