### PR TITLE
make translation more native

### PR DESCRIPTION
**Pull request by BilyZ98**
update zh-hans translation of starting-a-project.md ane make it more readable and more native to a native Chinese.

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by bungfut** [comment]
https://github.com/github/opensource.guide/pull/2524.patch

**Review by itsbagpack — APPROVED** [review]
Thank you for your contribution! I'll merge this as soon as the build is green.

**Comment by lordany** [comment]
Ok desr

**Comment by lordany** [comment]
What now

**Comment by lordany** [comment]
I need money
Sapa nation over here

**Comment by lordany** [comment]
We're goin to Asia yeeeeeee

**Comment by lordany** [comment]
Annie idibia

**Pull request merged**
