### PR TITLE
Add one missing character in Chinese translation

### PR DESCRIPTION
**Pull request by hezhizhen**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by maisoenaingtun** [comment]
{{Add-one-missing-character-in-Chinese-translation#2268}}

**Review by Oneill38 — APPROVED** [review]

**Comment by shanevz** [comment]
> - [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
> - [x] Have you explained what your changes do, and why they add value to the Guides?
> 
> **Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**
> 
> -----
>

**Review by jace833 — COMMENTED** [review]
黄冠龙

**Comment by jace833** [comment]
我

**Comment by PavelNehasil** [comment]
我

**Pull request merged**
