### PR TITLE
[zh-hans]Optimize sentences and keep them smooth

### PR DESCRIPTION
**Pull request by cxhello**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Review by ahpook — APPROVED** [review]
LGTM, thank you!

**Comment by cxhello** [comment]
@ahpook merge queue check failed.

**Comment by Lea29rp** [comment]
[GitHub Actions CI](https://github.com/github/opensource.guide/actions/workflows/tests.yml)

**Review by Aurimejia — COMMENTED** [review]
#3203

**Review by Aurimejia — COMMENTED** [review]
zh-hans]Optimiza oraciones y mantenlas fluidas #3203
Fusionado

**Comment by branden1992** [comment]
See what you can do about fixing everything for me on my accounts I want no restrictions

**Comment by Magdihamed** [comment]
0bd51bc18fac38dfc7e2e7f204dfe1b806c373d3

**Pull request merged**
