### PR TITLE
Added a translation for the file README in PT-BR.

### PR DESCRIPTION
**Pull request by MatheusTKoch**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

 Hi, its my first time contributing to the project, so i'm sorry for any mistakes, im still learning. I read the contributing file but didn't find any translation for the README file, so i made one for Brazilian Portuguese (my main language). If there is anything wrong please give your feedback and i will work on it. Thank you.

### CODE REVIEW

**Comment by Emekachuk** [comment]
Welcome

**Comment by Emekachuk** [comment]
Happy Sunday to you friends

**Comment by Anodam** [comment]
Adhdghgd

**Comment by Anodam** [comment]
Okay

**Comment by Anodam** [comment]
Welcome

**Comment by Anodam** [comment]
Okay

**Comment by MikeMcQuaid** [comment]
Thanks for the PR! We're not considering translating the README at this time so passing on this, sorry!

**Comment by MatheusTKoch** [comment]
@MikeMcQuaid No problem at all! If you have any translating jobs or anything i can help as a beginner in Javascript, please tell me and i will work on it. Thank you, and have a great week!

**Comment by faree321** [comment]
سلام،شما ایرانی هستین؟،  من یه مشکل برداشت ارز ایاس دارم و کد ممو
رو ننوشتم و به جای کد ممو همون ادرس ارز رو بجای کد کپی کردم ،الان ارز من
وجود داره ولی نمیدونم چطور میتونم اونو بر گردونم ،لطفا راهنمایی و کمک ،اگر
به هر مدرکی یا اسکرینترون شاتی هم نیاز بود دارم

**Pull request closed without merging**
