### PR TITLE
Translation into Polish

### PR DESCRIPTION
**Pull request by mbiesiad**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by mbiesiad** [comment]
Hi there! Really great project. Here is finished Polish version: https://github.com/mbiesiad/opensource.guide/tree/pl
I hope, you enjoy! Best regards

**Comment by mlinksva** [comment]
Thanks! There are some test failures to correct before merging, starting at https://github.com/github/opensource.guide/pull/1431/checks?check_run_id=462105742#step:7:890

Tests can be run locally also, run `script/test`.

**Comment by mbiesiad** [comment]
My pleasure! Installed Ruby & Bundler. Runned script/bootstrap and script/server. Opened http://localhost:4000. There I can generally just download 'test' script. What next?

**Comment by mbiesiad** [comment]
OK [WIP], I corrected these links errors a bit now

**Comment by mbiesiad** [comment]
Everythink corrected, looks fine now. But:
```
- _site/pl/legal/index.html
  *  internal image /assets/images/illos/.svg does not exist (line 0)
- _site/pl/starting-a-project/index.html
  *  External link https://github.com/github/opensource.guide/blob/master/code-of-conduct failed: 404 No error
```
etc. mainly 

> /.svg does not exist

**Comment by mlinksva** [comment]
Thanks! `internal image /assets/images/illos/.svg does not exist (line 0)` was being caused by a missing class field in leadership-and-governance.md. I pushed a few other small fixes. LGTM!

**Comment by mbiesiad** [comment]
My pleasure! Ok, thank you for your help and explaining! Best greetings

**Comment by mlinksva** [comment]
The translation is live at https://opensource.guide/pl/

**Pull request merged**
