### PR TITLE
PKG install update

### PR DESCRIPTION
**Pull request by endang121**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by walli2** [comment]
gh pr checkout 2535

**Comment by MaryJaneLove4** [comment]
Let's go

**Review by MaryJaneLove4 — APPROVED** [review]
Right

**Review by MaryJaneLove4 — APPROVED** [review]

**Review by MaryJaneLove4 — APPROVED** [review]

**Comment by endang121** [comment]
PKG install update

**Pull request closed without merging**
