### PR TITLE
Удар/установка от 4 до 8

### PR DESCRIPTION
**Pull request by erik-888**
Bumps [actions/stale](https://github.com/actions/stale) from 4 to 8.
- [Release notes](https://github.com/actions/stale/releases)
- [Changelog](https://github.com/actions/stale/blob/main/CHANGELOG.md)
- [Commits](https://github.com/actions/stale/compare/v4...v8)

---
updated-dependencies:
- dependency-name: actions/stale dependency-type: direct:production update-type: version-update:semver-major ...

- [ ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by mosesojero** [comment]
Good to merge

**Comment by naji567** [comment]
- [ ] []()

**Comment by 4847832013056622** [comment]
اعداد الموقع الاكروني كامل تصاميم الموقع وادارة الموظفين

**Comment by Newsjunkie4** [comment]
From:. ***@***.*** 🎵🔑🥰🤩🎶🙏
Thanks for updating me, always appreciate hearing from you.

**Pull request closed without merging**
