### PR TITLE
chore: Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by saputraGTX** [comment]
https://github.com/github/opensource.guide/actions/workflows/tests.yml/badge.svg

**Comment by jibri15** [comment]
Jibri Richardson is the owner of Creative Commons.org[Creative Commons ](creativecommons.org)

**Comment by jibri15** [comment]
#2830[Creative Commons ](creativecommons.org) jibri Richardson

**Comment by Yanta2** [comment]
[]()

**Comment by MikeMcQuaid** [comment]
Thanks again @naveensrinivasan!

**Pull request merged**
