### PR TITLE
chore: :pencil: change branch name from master to main

### PR DESCRIPTION
**Pull request by fabianoleittes**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

This is a simple change, using the **main** name instead of the  <strike>master</strike>

### CODE REVIEW

**Review by smashwilson — APPROVED** [review]
:+1: Thanks!

**Comment by djnikkib** [comment]
Can have a little help

**Review by 909496888 — COMMENTED** [review]
Allow privous on

**Review by bigjoe1973-debug — COMMENTED** [review]
How do I read it or even understand it

**Comment by bigjoe1973-debug** [comment]
I don't know what it is

**Comment by bigjoe1973-debug** [comment]
Can anyone help me with this

**Review by fido12 — COMMENTED** [review]
[](url)

**Pull request merged**
