### PR TITLE
Revert "Fixing commas and spanish expresions."

### PR DESCRIPTION
**Pull request by alaoy0225**
Reverts github/opensource.guide#2938

### CODE REVIEW

**Review by kenyonj — CHANGES_REQUESTED** [review]
Can you please elaborate in the PR body why this change is being proposed?

**Comment by asuender** [comment]
I guess this PR was opened by a bot ...

**Comment by kenyonj** [comment]
Please reopen in the future if necessary

**Comment by Farukkrw** [comment]
Hello

**Comment by yamommasofat** [comment]
It was a Freudian tap totally not what I was intending I didn't think it
went through I apologize

**Comment by Farukkrw** [comment]
Good

**Pull request closed without merging**
