### PR TITLE
Fix typo in article

### PR DESCRIPTION
**Pull request by chinghongfang**
In Chinese article, Fix some typos and make the sentence fluent in article "how-to-contribute".

- [ ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Review by deniseyu — APPROVED** [review]
Thanks for the contribution, @chinghongfang!

**Comment by deniseyu** [comment]
hi @chinghongfang, we had an issue with our CI - if you can merge main into your branch, the tests should automatically go green, and I'll be happy to merge this!

**Comment by chinghongfang** [comment]
Thanks for @deniseyu reviewing and guiding. I am new to open source contribution, and I am learning how it works. I am not sure if I have "merge main into your branch". But I have 
* pulled the latest changes into my local main branch, 
* merge local main branch into my branch.
Thanks for guiding.

**Comment by deniseyu** [comment]
@chinghongfang you got it exactly right! Thank you for your patience and welcome to open source 😄

**Pull request merged**
