### PR TITLE
Updated README.md file 

### PR DESCRIPTION
**Pull request by cruzz77**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----
Added some GIF's and Images. Hope this looks better than the earlier.

### CODE REVIEW

**Comment by Margiemagdoza** [comment]
> * [ ]  Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
> * [ ]  Have you explained what your changes do, and why they add value to the Guides?
> 
> **Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**
> 
> Added some GIF's and Images. Hope this looks better than the earlier.
Yes always followed

**Comment by Margiemagdoza** [comment]
😜😜😜

**Comment by ahpook** [comment]
This is not a helpful PR, it changes unrelated content and does not improve the site.

**Comment by cruzz77** [comment]
## PR: Improvements to the README.md

Hi Brother ,

I've made some updates to your **README.md** file in my forked repository. My goal was to enhance the clarity and overall presentation, making it easier to understand and more visually appealing. This is my first time to pull  a request on GitHub, so I'm still learning the process.

If you feel that any of the changes I've made could be improved or if there's anything you'd like to suggest, please feel free to let me know! I'm open to feedback and would love to make further improvements based on your suggestions.

Thanks for your time, and I look forward to your thoughts!

Kind regards,  
Cruzz_77

**Comment by cruzz77** [comment]
https://github.com/cruzz77/opensource.guide/blob/main/README.md

**Pull request closed without merging**
