### PR TITLE
Rename _articles/code-of-conduct.md to code-of-conduct.md

### PR DESCRIPTION
**Pull request by Domina585**
Bbnb

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by Domina585** [comment]
#928

**Comment by Domina585** [comment]
> Bbnb
> 
> * [x]  Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
> * [x]  Have you explained what your changes do, and why they add value to the Guides?
> 
> **Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

**Review by zahirpatel110 — COMMENTED** [review]
Test

**Review by zahirpatel110 — COMMENTED** [review]
#2607 #1837 #2597 #2606 #2603 
Duplicate of #1837

**Review by zahirpatel110 — COMMENTED** [review]
@zahirpatel110

**Comment by zahirpatel110** [comment]
https://github.com/github/opensource.guide/pull/2607#pullrequestreview-793576032

**Review by zahirpatel110 — COMMENTED** [review]
`

**Comment by christ1980** [comment]
Thx

**Review by christ1980 — COMMENTED** [review]
Thx

**Review by christ1980 — COMMENTED** [review]
Ok

**Review by Klp2121 — COMMENTED** [review]
Kiol

**Review by zahirpatel110 — COMMENTED** [review]
Done

**Pull request closed without merging**
