### PR TITLE
Translation `maintaining balance` into PL

### PR DESCRIPTION
**Pull request by olsza**
Complete translation into Polish (PL) of the new topic "Maintaining Balance for Open Source Maintainers"

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by olsza** [comment]
Please PR
@abbycabs
@UlisesGascon
@CBID2
@ahpook
@karasowles

**Review by underwoo16 — APPROVED** [review]

**Comment by CBID2** [comment]
Hey @underwoo16!:) This pull request was removed from the merge queue due to one of the tests failed.

**Comment by olsza** [comment]
> Hey @underwoo16!:) This pull request was removed from the merge queue due to one of the tests failed.

Hi @CBID2 
Which test has been spiked? because I can't see it.
If it crashed on me, I wouldn't be doing PR.
Give a link or screenshot of what and where the test crashed and I will fix it.

**Comment by CBID2** [comment]
> > Hey @underwoo16!:) This pull request was removed from the merge queue due to one of the tests failed.
> 
> 
> 
> Hi @CBID2 
> 
> Which test has been spiked? because I can't see it.
> 
> If it crashed on me, I wouldn't be doing PR.
> 
> Give a link or screenshot of what and where the test crashed and I will fix it.

Things are fine now @olsza! :) Can you help out with my PR?

**Comment by olsza** [comment]
> > > Hey @underwoo16!:) This pull request was removed from the merge queue due to one of the tests failed.
> > 
> > 
> > Hi @CBID2
> > Which test has been spiked? because I can't see it.
> > If it crashed on me, I wouldn't be doing PR.
> > Give a link or screenshot of what and where the test crashed and I will fix it.
> 
> Things are fine now @olsza! :) Can you help out with my PR? It's this one: #3098

OK
I will take a look at PR #3098 and try to fix it so that all is well.

**Pull request merged**
