### PR TITLE
fix a typo in farsi translation(here میگیرد is false, میگیرید is true)

### PR DESCRIPTION
**Pull request by bistcuite**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Review by smashwilson — APPROVED** [review]
Thanks!

**Comment by Antimeta88** [comment]
Hey BOZZ actualli,,ure a beast,,,i never seen somethin like this before,,,

**Comment by Antimeta88** [comment]
My placer!;)

**Comment by Antimeta88** [comment]
Thank to u ...

**Pull request merged**
