### PR TITLE
Fixed 404 broken line to solve issue 

### PR DESCRIPTION
**Pull request by Raphael-MOUQUIN**
to solve https://github.com/github/opensource.guide/pull/2463

### CODE REVIEW

**Comment by Raphael-MOUQUIN** [comment]
Fixed broken internal link 
c.f. issue https://github.com/github/opensource.guide/pull/2463#issuecomment-967002053

**Comment by Raphael-MOUQUIN** [comment]
to solve issue https://github.com/github/opensource.guide/pull/2463#issuecomment-967002053

**Comment by mylene611** [comment]
> to solve #2463

**Comment by nholden** [comment]
👋 Hi, @Raphael-MOUQUIN! Are these changes intended to address something in #2463? If so, could you please commit them to that branch (`Raphael-MOUQUIN:patch-1`) rather than opening a new PR?

**Pull request closed without merging**
