### PR TITLE
Polish Translation

### PR DESCRIPTION
**Pull request by P1X3L0V4**
- [X] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [X] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----
This PR is dedicated to add Polish translations. I plan to create all translations by the end of *November 15, 2019*

## Status
*Updated as of October 28, 2019*
### Initial files
- [X] Locale Data (_data/locales/pl.yml)
- [X] Index Page (_articles/pl/index.html)
### Articles
- [X] Best Practices for Maintainers (_articles/pl/best-practices.md)
- [ ] Building Welcoming Communities (_articles/pl/building-community.md)
- [ ] Your Code of Conduct (_articles/pl/code-of-conduct.md)
- [ ] Finding Users for Your Project (_articles/pl/finding-users.md)
- [ ] Getting Paid for Open Source Work (_articles/pl/getting-paid.md)
- [ ] How to Contribute to Open Source (_articles/pl/how-to-contribute.md)
- [ ] Leadership and Governance (_articles/pl/leadership-and-governance.md)
- [ ] The Legal Side of Open Source (_articles/pl/legal.md)
- [ ] Open Source Metrics (_articles/pl/metrics.md)
- [ ] Starting an Open Source Project (_articles/pl/starting-a-project.md)

### CODE REVIEW

**Comment by sschevy74** [comment]
Approved.  Thank you 

Sent from Yahoo Mail on Android 
 
  On Sun, Oct 13, 2019 at 6:56 AM, nehtechnine<notifications@github.com> wrote:   
@nehtechnine approved this pull request.

**Comment by Chasdaspaz** [comment]
pull request

**Comment by Chasdaspaz** [comment]
pull request

**Comment by Chasdaspaz** [comment]
pull request

**Comment by Chasdaspaz** [comment]
pull request

**Comment by Chasdaspaz** [comment]
pull request

**Comment by andrzej277** [comment]
Unlock

czw., 5 gru 2019, 08:15 użytkownik Chas Carter <notifications@github.com>
napisał:

**Comment by Chasdaspaz** [comment]
pull request

**Comment by mlinksva** [comment]
Closing this as a Polish translation was completed in #1431. Please feel free to make pull requests if there's anything about the translation you feel could be improved. Thanks!

**Pull request closed without merging**
