### PR TITLE
Modified Korean translations more natural

### PR DESCRIPTION
**Pull request by pilgwon**
- [V] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [V] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by pilgwon** [comment]
Oh i didn't know that i have to change heading title.
I'll change it! Thank you

**Comment by pilgwon** [comment]
I don't know why External Link 403 Error occurring for 'https://www.drupal.org/community-initiatives/drupal-core/usability'
How can i solve this error?

**Comment by mlinksva** [comment]
I think the dupal.org site must be doing some kind of throttling, but I can't tell what -- the site works for me from a web browser or wget, but not curl or tests, and changing the user agent doesn't help. So ignoring for now.

@pilgwon I noticed there's an older PR in progress to improve the Korean translation, #709. I haven't looked to see whether your updates touch the same material as that one. Maybe you can review #709 and/or @reverince can review this one. I guess that this one might be smaller in scope and could be either its branch could be merged into #709 or merged into master quickly?

**Comment by pilgwon** [comment]
Oh I don't know that translation in korean project is wip.
I'll close and wait for that project!

**Pull request closed without merging**
