### PR TITLE
docs: fixup for Contributor Covenant hyperlinks

### PR DESCRIPTION
**Pull request by jayaddison**
Adds the `www.` subdomain prefix to these hyperlinks, since the subdomainless-URL appears to not to redirect them any more.

This is reported upstream as EthicalSource/contributor_covenant#1425

Relates-to commit 24f9b31f6845d52f01d9cd9962ae5138ac866519.

Tested locally using the [development server](https://github.com/github/opensource.guide/blob/9d697019bac52453e56870e56f54250626000850/script/server).

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

### CODE REVIEW

**Comment by klaude** [comment]
For those watching, we fixed the DNS records at contributor-covenant.org. The original links should be working again.

**Comment by jayaddison** [comment]
Yep, these changes are no longer required; please feel free to close this pull request (as I'll probably do myself otherwise within a week or two).

**Comment by jmeridth** [comment]
@jayaddison nonetheless, thanks for watching out. We appreciate it.

**Comment by jmeridth** [comment]
@klaude thank you for the update.

**Comment by jayaddison** [comment]
You're welcome - thanks @jmeridth!

**Pull request closed without merging**
