### PR TITLE
Remove link to Contributor-ninja

### PR DESCRIPTION
**Pull request by calenrobinette**
removed link because https://contributor.ninja/ is no longer working.

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by mlinksva** [comment]
The website is up and https://github.com/contributor-ninja/contributor.ninja has recent activity. I hadn't visited before so am not sure how the site behaved before. Copying @xtuc who I believe runs the site and perhaps can confirm one way or the other.

**Comment by xtuc** [comment]
Thanks for pinging me!

I couldn't spend much time on the website lately but I can spend some time tomorrow to fix it, sorry.

**Comment by xtuc** [comment]
Ok sorry for the delail, https://contributor.ninja is working again.

**Comment by mlinksva** [comment]
Thanks @xtuc and thanks for reporting @calenrobinette.

**Pull request closed without merging**
