### PR TITLE
Improving grammar

### PR DESCRIPTION
**Pull request by yesnoruly**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

Corrected duplicate words from one quote and fixed case usage

### CODE REVIEW

**Review by jun102311 — COMMENTED** [review]
[]()

**Comment by jun102311** [comment]
기여 기여지칭

**Review by jun102311 — COMMENTED** [review]
승인하다

**Review by MikeMcQuaid — APPROVED** [review]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @yesnoruly!

**Comment by BigsteppA1** [comment]
Yes

**Pull request merged**
