### PR TITLE
Update and rename _articles/tr/index.html to _nesne/tr/index.html

### PR DESCRIPTION
**Pull request by bekoucak**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Review by bekoucak — COMMENTED** [review]
# # #bekoucak:patch-1 #

**Comment by krebsyba** [comment]
A222

**Review by ngothanhthai — COMMENTED** [review]
_nesne/tr/index.html

**Review by sarik20 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Comment by onewa0625** [comment]
그만보내세요

네이버 메일 앱에서 보냈습니다.
-----Original Message-----
보낸사람: "jace4411" <notifications@github.com>
받는사람: "github/opensource.guide" <opensource.guide@noreply.github.com>
참조: "Subscribed" <subscribed@noreply.github.com>
날짜: 2021.01.11 오전 00:53:29 (GMT+09:00)
제목: Re: [github/opensource.guide] Update and rename _articles/tr/index.html to _nesne/tr/index.html (#2107)

@jace4411 approved this pull request.

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Review by jace4411 — APPROVED** [review]

**Pull request closed without merging**
