### PR TITLE
Pr/3004

### PR DESCRIPTION
**Pull request by psyboy666**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by yamommasofat** [comment]
The rules have been followed by me, and have noticed that the project
(yamommasofat/nethermind) is fully functional. My participation has abided
to the criteria correctly. My apologies are in order if delinquency of mine
has been observed. The participation needing attention is being observed
and updated as soon as it will allow my participation to gain knowledge of
such overlooked or misunderstood path.
    Sincerely John Fuquarium

**Comment by yamommasofat** [comment]
6 protons 6 nutrons 6 electrons physical carbon copy

**Review by raul836 — COMMENTED** [review]
#94

**Comment by raul836** [comment]
#3005

**Review by armando0820 — COMMENTED** [review]
Bien

**Comment by raul836** [comment]
Bien

**Comment by raul836** [comment]
I want to know how to list a decentralized token to an exchange you don't know how to do that

**Comment by raul836** [comment]
https://i.ibb.co/yssMtBT/image-1-2-1.png

)
{
    "name": "VBNB",
    "type": "BEP20",
    "symbol": "VBNB",
    "decimals": 4,
    "website": "https://tokenworkcom.wordpress.com/#jp-carousel-50",
    "description": "VBNB es un token descentralizado echo en bcscan es un meme Coín ",
    "explorer": "https://bscscan.com/token/0x7E20f650Cd25B72813280933f2754d651601AE6B",
    "status": "active",
    "id": "0x7E20f650Cd25B72813280933f2754d651601AE6B",
    "links": [
        {
            "name": "twitter",
            "url": "https://twitter.com/RaulAra78303627"
        },
        {
            "name": "github",
            "url": "https://github.com/raul836/assets"
        },
        {
            "name": "telegrama",
            "url": "@ReporVBNB"
        },
        {
            "name": "papel blanco",
            "url": "https://tokenworkcom.wordpress.com/#jp-carousel-50"
        },
        {
            "name": "Reddit",
            "url": "https://www.reddit.com/user/Ral633/"
        },
        {
            "name": "coinmarketcap",
            "url": "https://coinmarketcap.com/dexscan/bsc/0x40968913544195fc0609f21a514cf26c30fbc7f7/"
        },
        {
            "name": "medio",
            "url": "https://medium.com/@rauldeleon_32774"
        },
        {
            "name": "Facebook",
            "url": "https://www.facebook.com/profile.php?id=100083171714836&mibextid=ZbWKwL"
        },
        {
            "name": "YouTube",
            "url": "https://youtube.com/@VBNBCHAIN"
        },
        {
            "name": "Blog",
            "url": "https://www.geckoterminal.com/es/bsc/pools/0x40968913544195fc0609f21a514cf26c30fbc7f7"
        },
        {
            "name": "documentos",
            "url": "https://tokenworkcom.wordpress.com/#jp-carousel-50"
        },
        {
            "name": "telegram",
            "url": "https://t.me/"
        },
        {
            "name": "gorjeo",
            "url": "https://twitter.com/RaulAra78303627"
        },
        {
            "name": "telegram_news",
            "url": "https://t.me/@ReporVBNB"
        },
        {
            "name": "blog",
            "url": "https://coinmarketcap.com/dexscan/bsc/0x40968913544195fc0
{
    "name": "VBNB",
    "type": "BEP20",
    "symbol": "VBNB",
    "decimals": 4,
    "website": "https://tokenworkcom.wordpress.com/#jp-carousel-50",
    "description": "VBNB es un token descentralizado echo en bcscan es un meme Coín ",
    "explorer": "https://bscscan.com/token/0x7E20f650Cd25B72813280933f2754d651601AE6B",
    "status": "active",
    "id": "0x7E20f650Cd25B72813280933f2754d651601AE6B",
    "links": [
        {
            "name": "twitter",
            "url": "https://twitter.com/RaulAra78303627"
        },
        {
            "name": "github",
            "url": "https://github.com/raul836/assets"
        },
        {
            "name": "telegrama",
            "url": "@ReporVBNB"
        },
        {
            "name": "papel blanco",
            "url": "https://tokenworkcom.wordpress.com/#jp-carousel-50"
        },
        {
            "name": "Reddit",
            "url": "https://www.reddit.com/user/Ral633/"
        },
        {
            "name": "coinmarketcap",
            "url": "https://coinmarketcap.com/dexscan/bsc/0x40968913544195fc0609f21a514cf26c30fbc7f7/"
        },
        {
            "name": "medio",
            "url": "https://medium.com/@rauldeleon_32774"
        },
        {
            "name": "Facebook",
            "url": "https://www.facebook.com/profile.php?id=100083171714836&mibextid=ZbWKwL"
        },
        {
            "name": "YouTube",
            "url": "https://youtube.com/@VBNBCHAIN"
        },
        {
            "name": "Blog",
            "url": "https://www.geckoterminal.com/es/bsc/pools/0x40968913544195fc0609f21a514cf26c30fbc7f7"
        },
        {
            "name": "documentos",
            "url": "https://tokenworkcom.wordpress.com/#jp-carousel-50"
        },
        {
            "name": "telegram",
            "url": "https://t.me/"
        },
        {
            "name": "gorjeo",
            "url": "https://twitter.com/RaulAra78303627"
        },
        {
            "name": "telegram_news",
            "url": "https://t.me/@ReporVBNB"
        },
        {
            "name": "blog",
            "url": "https://coinmarketcap.com/dexscan/bsc/0x40968913544195fc0609f21a514cf26c30fbc7f7/"
        },
        {
            "name": "foro",
            "url": "0x40968913544195fc0609f21a514cf26c30fbc7f7"
        }
    ],
    "tags": [
        "26",
        "memes"
    ]
} 
< centro >< img src = ' [url=https://ibb.co/yssMtBT][img]https://i.ibb.co/yssMtBT/image-1-2-1.png][/url] ' altura = "200" ></ centro609f21a514cf26c30fbc7f7/"
        },
        {
            "name": "foro",
            "url": "0x40968913544195fc0609f21a514cf26c30fbc7f7"
        }
    ],
    "tags": [
        "26",
        "memes"
    ]
}

**Pull request closed without merging**
