### PR TITLE
Add a `maintaining balance` file to languages

### PR DESCRIPTION
**Pull request by olsza**
Compiled file on Maintaining Balance in all currently available languages.
In this way, the untranslated document will be available after EN, and the language maintainers will see that there is a document to be translated.

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by olsza** [comment]
Please CR and suggestions
@abbycabs
@UlisesGascon
@CBID2
@ahpook
@karasowles

**Comment by UlisesGascon** [comment]
LGTM! I can't approve it due permissions restrictions, but great work @olsza! 👍

**Comment by UlisesGascon** [comment]
@olsza feel free to join us (if you are not already) in https://maintainers.github.com/. You might find this discussion super interesting https://github.com/community/maintainers/discussions/337 😄

**Comment by olsza** [comment]
> @olsza feel free to join us (if you are not already) in https://maintainers.github.com/. You might find this discussion super interesting https://github.com/community/maintainers/discussions/337 😄

Thanks to
I'll join as soon as GitHub accepts me

**Comment by olsza** [comment]
> > @olsza feel free to join us (if you are not already) in https://maintainers.github.com/. You might find this discussion super interesting https://github.com/community/maintainers/discussions/337 😄
> 
> Thanks to I'll join as soon as GitHub accepts me

I have already sent 2 requests for @GitHub to accept me and allow me to participate in the discussion, but no news for a week, even though it was written to 72h.
I don't know if I should post a 3rd time or wait?

**Comment by UlisesGascon** [comment]
> I don't know if I should post a 3rd time or wait?

I will suggest to wait, It can take a while until the invitations are accepted 😉 

Maybe @karasowles can grant you access 🤔

**Comment by RikValens1988** [comment]
Thanks you friends

**Comment by RikValens1988** [comment]
Thanks you fryends

**Comment by RikValens1988** [comment]
Thanks you friends

**Comment by zkoppert** [comment]
Thanks for adding @olsza ! I'm hoping this will lead to more translations of the article. 🚀

**Pull request merged**
