### PR TITLE
apsist025350@gmail.com

### PR DESCRIPTION
**Pull request by apsist025350**
- [ ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/gh-pages/CONTRIBUTING.md)?
- [ ] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by apsist025350** [comment]
Line

**Comment by apsist025350** [comment]
Line

**Comment by thaJeztah** [comment]
Spambot; I already reported this account through GitHub support

**Comment by apsist025350** [comment]
Line

**Pull request closed without merging**
