### PR TITLE
[WIP] Proofreading of zh-CN part

### PR DESCRIPTION
**Pull request by WordlessEcho**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/gh-pages/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

It just a simply check of most typing mistake, most syntax mistake and a bit translate mistake.
This PR will be the first, I will proofread more the once time.

### CODE REVIEW

**Comment by schneems** [comment]
Looks like tests are failing. Looks like master is also failing, but with different errors https://travis-ci.org/github/opensource.guide/builds/351805696

**Comment by MikeMcQuaid** [comment]
@WordlessEcho Thanks for the PR! These errors will need to be addressed:

- _site/zh-cn/best-practices/index.html
  *  linking to ../building-community/#share-ownership-of-your-project, but share-ownership-of-your-project does not exist (line 315)
     <a href="../building-community/#share-ownership-of-your-project">一起管理项目</a>
  *  linking to internal hash #Take%20care%20of%20yourself%20first! that does not exist (line 138)
     <a href="#Take%20care%20of%20yourself%20first!" class="d-block py-3 px-3">首先照顾好自己</a>
- _site/zh-cn/leadership-and-governance/index.html
  *  linking to ../building-community/#share-ownership-of-your-project, but share-ownership-of-your-project does not exist (line 219)
     <a href="../building-community/#share-ownership-of-your-project">共享所有权</a>
- _articles/zh-cn/best-practices.md
  * 249:6-249:7  warning  Expected a straight apostrophe: `'`, not `’`  apostrophe  retext-quotes

**Comment by MikeMcQuaid** [comment]
Another error I'm afraid: 

- _site/zh-cn/best-practices/index.html
  *  linking to internal hash #Take%20care%20of%20yourself%20first! that does not exist (line 138)
     <a href="#Take%20care%20of%20yourself%20first!" class="d-block py-3 px-3">首先照顾好自己</a>

**Comment by MikeMcQuaid** [comment]
@WordlessEcho Still failing I'm afraid. You can test this locally by running `./script/test`

**Comment by WordlessEcho** [comment]
@MikeMcQuaid I know where the problem is now, thanks for you keep following. : )

**Comment by MikeMcQuaid** [comment]
@WordlessEcho I'd recommend running the tests locally so you know if the issue is fixed before you push more commits. Also you can compare to the other translations or existing code.

**Comment by WordlessEcho** [comment]
OK, I will do it locally.

**Pull request closed without merging**
