### PR TITLE
[German translation]: Remove 'Beitragsarten' and fix some minor stuff

### PR DESCRIPTION
**Pull request by asuender**
- [X] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

This should fix minor typos and some translations as the following:
* Rephrase sentence containing "Beitragsarten" (which itself is a 1:1 translation of "types of contributions" - this sounds weird in German)
* Use "einen Pull Request" instead of "ein Pull Request" as it seems to be more common
* Remove unnecessary dots & commas

### CODE REVIEW

**Review by Santiagosaiz — COMMENTED** [review]
****Santiagosaiz4inittowinit

**Review by Athis83 — COMMENTED** [review]
Super

**Review by Athis83 — COMMENTED** [review]
Super

**Comment by mehdirahiminia** [comment]
Hello, how can you help me? My account is broken

**Comment by Kodakskush111** [comment]
> 

How is you 😘😘😘😘

**Pull request merged**
