### PR TITLE
Merge pull request #2985 from asuender/main

### PR DESCRIPTION
**Pull request by Avsaribo**
[German translation]: Remove 'Beitragsarten' and fix some minor stuff

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by Avsaribo** [comment]
mona

**Comment by Avsaribo** [comment]
Avs

**Comment by olsza** [comment]
CR = to be closed

**Comment by ahpook** [comment]
SPAM, locked and reported.

**Pull request closed without merging**
