### PR TITLE
Improve some chinese translation

### PR DESCRIPTION
**Pull request by freeman0432**
- [X] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [X] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----
Fix some typo and modify some not elegant translations

### CODE REVIEW

**Comment by freeman0432** [comment]
@MikeMcQuaid Help me review it.

**Comment by MikeMcQuaid** [comment]
Thanks @freeman0432!

**Comment by freeman0432** [comment]
> Thanks @freeman0432!
You are welcome.

**Comment by freeman0432** [comment]
You are welcome.

**Comment by freeman0432** [comment]
You are welcome.@MikeMcQuaid

**Pull request merged**
