### PR TITLE
Fix editorial inconsistencies or inaccuracies

### PR DESCRIPTION
**Pull request by Raphael-MOUQUIN**
Improved translation

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

### CODE REVIEW

**Comment by MaryJaneLove4** [comment]
I can't understand IT. I Lost 1.44 BNB. HELP PLEASE


Dne st 7. 7. 2021 18:40 uživatel Raphael-MOUQUIN ***@***.***>
napsal:

**Comment by itsbagpack** [comment]
Hi @Raphael-MOUQUIN, thank you for your contribution! It looks like there is a [failing test](https://github.com/github/opensource.guide/pull/2463/checks?check_run_id=3127421270) associated with your PR. Could you take a look and fix it? We'll be able to re-review your PR after that. Thank you!

**Comment by Raphael-MOUQUIN** [comment]
Hi all

OK, better that way. Thanks for your collaboration

Best regards

**Comment by Aparus** [comment]
Hi. On the page: https://opensource.guide/code-of-conduct/
the link "Ada Initiative" https://adainitiative.org/2014/02/18/howto-design-a-code-of-conduct-for-your-community/
is not working. 
It causes failure of tests.

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
Please fix the CI failures: https://github.com/github/opensource.guide/pull/2463/checks?check_run_id=3532339409#step:7:35

**Comment by Mint-6263** [comment]
:blush:

**Review by danielski1988 — APPROVED** [review]

**Comment by octocat69** [comment]
gh pr checkout 10141

**Comment by octocat69** [comment]
gh pr checkout 10141

**Comment by octocat69** [comment]
https://twitter.com/sanjithwarner/status/1437084250520567809?s=19

**Comment by Raphael-MOUQUIN** [comment]
hi, there are still issues, why don't you merge?

**Review by Raphael-MOUQUIN — COMMENTED** [review]
Reviewed and OK

**Comment by MikeMcQuaid** [comment]
@Raphael-MOUQUIN I waited for a month for CI failures to be resolved.

**Comment by Raphael-MOUQUIN** [comment]
@MikeMcQuaid oh! yes ,  it happens sometimes. Nevertheless you managed it then ?

**Comment by Raphael-MOUQUIN** [comment]
So all the improvement job that has been done is lost ????

**Comment by MikeMcQuaid** [comment]
@Raphael-MOUQUIN I've reopened the PR. Please fix the CI status in the next week or we'll need to close this again, thanks.

**Comment by Raphael-MOUQUIN** [comment]
@MikeMcQuaid  Thanks! and sorry for your precious time. I just expected to help and now 
we can see this replacement link is dead too. Google cache for that entry has been cleared.

**Comment by MikeMcQuaid** [comment]
@Raphael-MOUQUIN this is the issue that needs fixed with your changes: https://github.com/github/opensource.guide/runs/4189065585?check_suite_focus=true#step:7:37

**Comment by Raphael-MOUQUIN** [comment]
sorry, still don't get it. Cannot update my commit to  validate it. Sorry, so much time/work lost due to a link on the page? An old link that hat nothing to do with the submitted improvements.?  Anyway, I cannot manage to update that link that does NOT belong to the modified file I try to submit....

**Comment by Raphael-MOUQUIN** [comment]
Still trying to understand the new way GitHub works , 
feeling like to give up  but  it's an opportunity to learn , yeah, i'll try later, already lost numerous minutes trying to fix the CI issue. Thanks anyway to all. Have a good day

**Comment by sas1354** [comment]
- [ ] - https://github.com/github/opensource.guide/pull/2463

**Comment by MikeMcQuaid** [comment]
Still failing I'm afraid @Raphael-MOUQUIN. You may want to run this in a local web server to figure out the name of the generated anchor.

**Comment by MikeMcQuaid** [comment]
https://github.com/github/opensource.guide/runs/4189939137?check_suite_focus=true#step:7:37

**Review by mylene611 — COMMENTED** [review]
> ``

**Comment by mylene611** [comment]
> Hi @Raphael-MOUQUIN, thank you for your contribution! It looks like there is a [failing test](https://github.com/github/opensource.guide/pull/2463/checks?check_run_id=3127421270) associated with your PR. Could you take a look and fix it? We'll be able to re-review your PR after that. Thank you!

**Review by Hjordaan2002 — COMMENTED** [review]
Good

**Comment by kenyonj** [comment]
Please feel free to open this back up when you can address the failing test. Thank you.

**Pull request closed without merging**
