### PR TITLE
Fix typo in the starting-a-project.md (Japanese translation)

### PR DESCRIPTION
**Pull request by parroty**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### Change (一分 → 一部)
It's a minor one, but I've found a typo in the Japanese version.
(I couldn't find any other issues, due to high-quality translation 😃).

### Notes
- Corresponding Google Translate (`part of your project's brand`)
    - https://translate.google.com/?hl=en&sl=auto&tl=ja&text=part%20of%20your%20project%27s%20brand&op=translate
- Similar translation in other location
    - English (`part of your project's brand`)
         - https://github.com/github/opensource.guide/blob/main/_articles/starting-a-project.md?plain=1#L240
    - Japanese (`プロジェクトのブランドの一部`)
         - https://github.com/github/opensource.guide/blob/main/_articles/ja/starting-a-project.md?plain=1#L240

### CODE REVIEW

**Comment by parroty** [comment]
It seems the test is failing on accessing `kindlegen.s3.amazonaws.com`, but I'm afraid I haven't been able to find the solution...

**Comment by smashwilson** [comment]
Yeah, the build is failing for reasons unrelated to these changes. Maybe it'll be a transient thing? I'll try to rebuild in a day or so and see if it resolves itself, and if not I'll hunt for other solutions.

**Comment by MagnoliaSlimMarket** [comment]
Hello, So I was hoping to be able to refrain from asking for help immediately by offering up a lot so brilliant question for assistance in guidance on something I'm working on that can be completely taken as disrespectful or completely unrelated to the task at hand.

With that being said.
It would be greatly appreciated if youassist me with an error code that was provided to me which states, UTXO is missing TXHEX of the input which is required by PSDT for non-Segwit input.

**Comment by Majidbeigloo** [comment]
Rest factory

**Review by Majidbeigloo — COMMENTED** [review]
- [ ] - - Rest factory @Majidbeigloo @parroty @smashwilson @MagnoliaSlimMarket @Majidbeigloo @iOSjNaGeR @Majidbeigloo @bruce @bensherman @Majidbeigloo @iOSjNaGeR @Majidbeigloo @mtodd @mtodd @bruce @mtodd @mathias @patrickt @rufo @theinterned @MagnoliaSlimMarket @iOSjNaGeR @zmoazeni @mtodd @mislav @matthewd @arthurschreiber @bratsche @rufo @theinterned @fermion @lynnwallenstein @rufo @parroty @febuiles @cdb @keeran @mislav @kjg @patrickt @lynnwallenstein @skalnik

**Review by nholden — APPROVED** [review]
Thanks for this contribution! 💖

**Pull request merged**
