### PR TITLE
[WIP] Arabic translation

### PR DESCRIPTION
**Pull request by ibrasho**
- [X] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [X] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**
-----

This PR is a WIP to translate opensource.guide to Arabic.

#### Articles translation completed

- [ ] Best Practices
- [ ] Building Community
- [ ] Code of Conduct
- [ ] Finding Users
- [x] Getting Paid
- [ ] How to Contribute
- [ ] Leadership and Governance
- [ ] Legal
- [ ] Metrics
- [ ] Starting a project

#### Other items:
- [ ] RTL styling

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Hey, thanks for the PR! Need to fix the test failures here: 
https://travis-ci.org/github/opensource.guide/builds/410079074

**Comment by MikeMcQuaid** [comment]
@ibrasho Ping on the test failures.

**Comment by koyemanaung** [comment]
support

**Comment by Anniejones40** [comment]
te="1548556922070" type="2" body="I agree 100 percent!!" read="1"  service_center="" name="" />
 <sms address="4172740993" time="Jan 26, 2019 8:42:02 PM"  date="1548556922000" type="2" body="I agree 100 percent!!" read="1"  service_center="" name="" />
 <sms address="4172740993" time="Jan 26, 2019 8:41:15 PM"  date="1548556875359" type="1" body="g what they deserve, that&apos;s  between us I hope. " read="1" service_center="" name="" />
 <sms address="4172740993" time="Jan 26, 2019 8:41:15 PM"  date="1548556875000" type="1" body="g what they deserve, that&apos;s  between us I hope. " read="1" service_center="" name="" />
 <sms address="4172740993" time="Jan 26, 2019 8:41:00 PM"  date="1548556860230" type="1" body="Hey, please don&apos;t repeat that  or this...I just think it&apos;s funny cuz I know they f&apos;d us  both!!! They aren&apos;t very nice people &amp; I see it as they are  gettin" read="1" service_center="" name="" />
 <sms address="4172740993" time="Jan 26, 2019 8:41:00 PM"  date="1548556860000" type="1" body="Hey, please don&apos;t repeat that  or this...I just think it&apos;s funny cuz I know they f&apos;d us  both!!! They aren&apos;t very nice people &amp; I see it as they are  gettin" read="1" service_center="" name="" />
 <sms address="4172812073" time="Jan 26, 2019 7:48:03 PM"  date="1548553683848" type="2" body="K" read="1" service_center=""  name="" />
 <sms address="4172812073" time="Jan 26, 2019 7:48:03 PM"  date="1548553683000" type="2" body="K" read="1" service_center=""  name="" />
 <sms address="4172812073" time="Jan 26, 2019 7:45:09 PM"  date="1548553509403" type="1" body="Idk ill message in  bit when im  ready:)" read="1" service_center="" name="" />
 <sms address="4172812073" time="Jan 26, 2019 7:45:09 PM"  date="1548553509000" type="1" body="Idk ill message in  bit when im  ready:)" read="1" service_center="" name="" />
 <sms address="4172812073" time="Jan 26, 2019 7:44:11 PM"  date="1548553451201" type="2" body="Do you know how much longer  you&apos;re gonna be hanging? Just wondering " read="1"  service_center="" name="" />
 <sms address="4172812073" time="Jan 26, 2019 7:44:11 PM"  date="1548553451000" type="2" body="Do you know how much longer  you&apos;re gonna be hanging? Just wondering " read="1"  service_center="" name="" />
 <sms address="4172933576" time="Jan 26, 2019 1:05:05 PM"  date="1548529505678" type="1" body="Okay thanks " read="1"  service_center="" name="" />
 <sms address="4172933576" time="Jan 26, 2019 1:05:05 PM"  date="1548529505000" type="1" body="Okay thanks " read="1"  service_center="" name="" />
 <sms address="14172933576" time="Jan 26, 2019 1:04:27 PM"  date="1548529467035" type="2" body="Hi this is , Christian&apos;s mom.  This is my number in case he forgets it :)" read="1" service_center=""  name="" />
 <sms address="14172933576" time="Jan 26, 2019 1:04:27 PM"  date="1548529467000" type="2" body="Hi this is , Christian&apos;s mom.  This is my number in case he forgets it :)" read="1" service_center=""  name="" />
 <sms address="31681" time="Jan 26, 2019 10:39:33 AM"  date="1548520773410" type="1" body="CAR-MART: Payment reminder, visit  car-mart.com/pay/069 for payment options. Text STOP to cancel."  read="1" service_center="" name="" />
 <sms address="31681" time="Jan 26, 2019 10:39:33 AM"

**Comment by nwaf111a** [comment]
Thank you for your efforts

**Comment by Himallkhan** [comment]
Nice

**Comment by juliana0101** [comment]
Quero contribuir j.baronee@hotmail.com

**Comment by jor514** [comment]
thanks

**Comment by jor514** [comment]
yes

**Comment by jor514** [comment]
cfbfc84

**Comment by jor514** [comment]
thanks

**Comment by MikeMcQuaid** [comment]
Closing this as it's inactive and has failing CI. Sorry!

**Comment by ibrasho** [comment]
No worries @MikeMcQuaid . If anyone wants to pick this up, please feel free.

**Comment by X7md** [comment]
Any updates?

**Pull request closed without merging**
