### PR TITLE
Add pt-br translation to "Maintaining Balance for Open Source Maintainers"

### PR DESCRIPTION
**Pull request by deadpyxel**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

In this PR I am proposing a translated version for the aforementioned article in Brazilian Portuguese. If there are any changes needed please let me  know.

### CODE REVIEW

**Comment by deadpyxel** [comment]
Not really sure why HTML-Proofer is accusing an error when locally it is finishing successfully.

**Comment by deadpyxel** [comment]
Could someone help me verify why the test suite is failing on Github Actions but running successfully locally?

**Comment by ahpook** [comment]
@deadpyxel Please rebase your PR onto main, there was an unrelated problem that was causing the tests to fail.

**Comment by deadpyxel** [comment]
Thanks @ahpook that was it!

**Review by ahpook — APPROVED** [review]
Thanks for the contribution!

**Comment by Sweetilona3** [comment]
Ok

**Comment by jorgerios2800** [comment]
Ok

**Pull request merged**
