### PR TITLE
Fix typo and incorrect links

### PR DESCRIPTION
**Pull request by lc-soft**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

- Fix incorrect link: `https://github.com/liadbiz/opensource-contribute-guide-chinise/blob/master/github-open-source-guide-02.md` => `../starting-a-project/#writing-a-readme`
- Fix typo: 
    - `正式你这样的人们使得` => `正是你这样的人们使得`
    - `对初次光临社区对人们表示欢迎` => `对初次光临社区的人们表示欢迎`
    - `社区对流程是啥样的` => `社区的流程是什么样的`
- Cancel the translation of file names, I think the file name should remain the same, no translation required

### CODE REVIEW

**Comment by lc-soft** [comment]
@jaredtl4587 Maybe you can use Google Translate to translate the modified text and compare the original English text. If they mean almost the same, it is correct.

**Comment by MikeMcQuaid** [comment]
@lc-soft  Is this still a problem? If so, could you resolve the conflicts. Sorry for the delay!

**Comment by lc-soft** [comment]
@MikeMcQuaid OK, I will fix it.

**Comment by MikeMcQuaid** [comment]
Thanks for another contribution, @lc-soft, you rock!

**Pull request merged**
