### PR TITLE
Update ru.yml

### PR DESCRIPTION
**Pull request by ViktorOn**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)? +
- [x] Have you explained what your changes do, and why they add value to the Guides? +

This is how it looked in Russian :)
image

### CODE REVIEW

**Comment by 1NITTY** [comment]
ViktorOn:patch-1

**Review by Mitumaru — COMMENTED** [review]
Yea

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @ViktorOn!

**Comment by Joterdan** [comment]
> Muito obrigado pela sua primeira contribuição! Sem pessoas como você enviando PRs, não poderíamos executar este projeto. Você arrasa, @ViktorOn !

**Comment by Antimeta88** [comment]
Isnt wrote in rusian

**Comment by Antimeta88** [comment]
Is french

**Comment by Antimeta88** [comment]
If u dont have to find all the contributors with this.
gem 'rubyzip'

**Comment by Antimeta88** [comment]
We can use my apalache

**Comment by Antimeta88** [comment]
Sorry

**Comment by Antimeta88** [comment]
Made or used apalache from the head of this proyect

**Comment by Antimeta88** [comment]
Is realy nesesary licesed after build

**Comment by Antimeta88** [comment]
And then

**Comment by Antimeta88** [comment]
Is done #get out of here#

**Comment by ViktorOn** [comment]
> Is done #get out of here#

You feels bad?

**Comment by Antimeta88** [comment]
Not at all

**Comment by Antimeta88** [comment]
Strong evidence & codes for build

**Comment by Antimeta88** [comment]
Licenced $on

**Comment by tackoman** [comment]
> - [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)? +
> - [x] Have you explained what your changes do, and why they add value to the Guides? +
> 
> This is how it looked in Russian :)
> image
> 
> 
>

**Comment by Alucaz2022** [comment]
- [ ] #- [ ] 　image@[__](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/releases/tag/1.45.2)

**Pull request merged**
