### PR TITLE
First contribution in 5 minutes

### PR DESCRIPTION
**Pull request by sramakrishnan247**
Added https://roshanjossey.github.io/first-contributions/ to finding a project to contribute to section.
This is the best place for any new developer to start. It teaches the basics of push, pull and fork by working hands on. I made my first contribution only because of this and might be useful for other newbies like me.

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/gh-pages/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by sramakrishnan247** [comment]
The failure reasons from the testing log:
 *  External link https://news.ycombinator.com failed: got a time out (response code 0)
 *  External link https://news.ycombinator.com/item?id=7531689 failed: got a time out (response code 0)

The above two websites work. I have tested them personally.
Please check the issue and remove the bug.

**Comment by nayafia** [comment]
Hi @sramakrishnan247, thanks for the suggestion! I think this fits better under the "Opening a pull request section", in this paragraph:

> If this is your first pull request, check out Make a Pull Request, which kentcdodds created as a free walkthrough resource.

The website you link to doesn't seem to provide unique value beyond the other links in that list; however, I like the idea of linking to [the repo](https://github.com/Roshanjossey/first-contributions) which provides a visual step-by-step walkthrough and a "real" repository to try it out on. I don't think we mention any resources like that currently.

Want to add it to that paragraph above? It can go in the same sentence after Make a Pull Request. Perhaps highlight that MaPR is a video tutorial, and this is a walkthrough and repository you can practice on.

**Comment by Roshanjossey** [comment]
@nayafia, I've submitted a pull request to address your comment. Please review.

**Comment by nayafia** [comment]
Closed via https://github.com/github/opensource.guide/pull/484.

**Pull request closed without merging**
