### PR TITLE
Update building-community.md in zh_tw

### PR DESCRIPTION
**Pull request by PichuChen**
Minor change, fix type 好的說明文建會 => 好的說明文件會

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by rmathew1992** [comment]
Thanks so much for your contribution! Happy to merge this once all of the tests pass. Thanks!

**Comment by PichuChen** [comment]
@rmathew1992 Sorry but I think there is a problem with the test. The test has been blocked by 2 external links, it shows 403, but I didn't modify them. So I'm not sure what to do.

**Comment by rmathew1992** [comment]
Oh, interesting re-running the build fixed the problem.

But this looks good to me. Thanks for your contribution!

**Review by rmathew1992 — APPROVED** [review]

**Review by mohammadahmadi98 — COMMENTED** [review]
Duplicate of #

>

**Comment by STRAWMANSTEVENYAWNEY** [comment]
071947            Fuck69$$     Other accounts gmail micro Babygirl01## or
$$ or ** thanks

**Review by phoothellchit2000 — COMMENTED** [review]
>  #792

**Review by ruksina25 — COMMENTED** [review]
❤️

**Pull request merged**
