### PR TITLE
adds poppins and reviews lists of first-timers resources

### PR DESCRIPTION
**Pull request by abilioesteves**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

This PR adds the [Poppins](https://github.com/bancodobrasil/poppins) project to the list of resources for first-timers.

Poppins is a manifesto that states the importance of having entire open source projects focused on beginners and first contributors and how to do guides. A project is considerate a "Poppins project" if it is mainly managed to help beginners to level up their skills and increase their experience with OSS in a mentorship community atmosphere.

-----

As a corollary of this PR, I noticed some translation inconsistencies with the list of resources for first-timers. This PR also fixes that.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks @abilioesteves! Are you at all affiliated with the Poppins project?

**Comment by abilioesteves** [comment]
Hello @MikeMcQuaid! I believe I'm indirected affiliated. 

The organization behind the project is my client, and I help run their open source lab ([labbsr0x](https://github.com/labbsr0x)). The Poppins project was not authored by me, but the minds behind it are from the same team that runs the lab. I occasionally contribute to the Poppins project, but with no commit privileges.

Either way, I believe the project is very well structured and may be a good resource for open source beginners :)

**Comment by MikeMcQuaid** [comment]
Hi @abilioesteves, I'm afraid we'd rather wait until someone otherwise unaffiliated submits this. Sorry (and thanks for the full disclosure). We'd accept the non-Poppins changes if you're interested?

**Comment by abilioesteves** [comment]
No problems. I understand! :) I will change the commit to remove references to the Poppins project. Thank you!

**Comment by abilioesteves** [comment]
@MikeMcQuaid, done!

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @abilioesteves!

**Pull request merged**
