### PR TITLE
I18n Fr

### PR DESCRIPTION
**Pull request by fbenariac**
This pr is about adding French lang on this guide.
Take care :wink: 

- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?
 
**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by mlinksva** [comment]
Thanks @fbenariac! Is this translation complete as far as you know?

If so, hopefully we can get another French speaker to review before merging.

**Comment by fbenariac** [comment]
Yes it is. 
Thank you for your reply. ;-)

**Comment by mlinksva** [comment]
@chuttarin and @luchogil96 thanks for your approvals. Could you confirm that you are French speakers and have at least skimmed the proposed translation? Sometimes it's hard to tell from code reviews with no commentary! 😄

**Comment by mlinksva** [comment]
I'm going to go ahead and merge this. If there are improvements to be made, anyone is welcome to submit pull requests. Thanks @fbenariac!

**Comment by fbenariac** [comment]
@mlinksva : Many thanks to you :+1:

**Pull request merged**
