### PR TITLE
check current translated files

### PR DESCRIPTION
**Pull request by pipobarari**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

I translated some part to Italian, but I wanted somebody else to check my progress, there are the folders and respective files for it = italian.

Regards

### CODE REVIEW

**Comment by Dispatchermillie** [comment]
Send payment $100

**Comment by ahpook** [comment]
This is great, thank you @pipobarari for the translation and good metadata. 

Do you know another Italian-speaking user who can check these translations? I watch bicycle racing with commentary in Italian but that does not help much here! 😸 

Are you planning to add more files / commits or should I merge this as it is today?

**Comment by pipobarari** [comment]
Im not able to continue translating the remaining files unlucky, and I don't know any other Italian who can help us either unfortunately.

Thanks for answering!

**Comment by RhondaRay** [comment]
CONTRIBUTING.mdAn open-source tool-augmented conversational language model from Fudan University

natural-language-processingdeep-learningtext-generationdialogue-systemslarge-language-modelschatgpt

Updated on Jul 10 Python

**Comment by Justin6689** [comment]
Good luck on your work day so sweet baby

**Comment by Justin6689** [comment]
Needs some help with that one

**Comment by Justin6689** [comment]
pipobarari:it you are bad

**Comment by Justin6689** [comment]
Duplicate of #
```

```

**Comment by ahpook** [comment]
I'll go ahead and merge this to get your good work out there, hopefully other people will pick it up in the future. Thank you!

**Review by ahpook — APPROVED** [review]
LGTM, in the absence of another Italian speaker to review I'm going to go ahead and merge.

**Comment by jacopobr** [comment]
Hello @ahpook. I am a native Italian speaker and will check the translations before the merge. Or you could merge and I'll open a new branch to translate what is missing. What do you prefer?

**Comment by zkoppert** [comment]
@jacopobr I am planning to merge this in. If you could open another branch/pull request with any revisions that would be much appreciated!

**Comment by zkoppert** [comment]
@pipobarari It looks like there are some errors coming up in the test that looks for valid links. Can you check [the results](https://github.com/github/opensource.guide/actions/runs/6330162603/job/17191942718?pr=3072) and see if that is something you can correct?

**Comment by jacopobr** [comment]
Hello @zkoppert, as I was taking as example the [pull requests on fork for German translation](https://github.com/katrinleinweber/opensource.guide/pulls?q=is%3Apr+is%3Aclosed) mentioned in the `translation.md` file, I opened two PRs to @pipobarari's fork since he was the one starting the translation. 
Do you still prefer me to open new a branch/pr?

**Comment by zkoppert** [comment]
@jacopobr Oh ok. Feel free to contribute to this branch in that case.

**Comment by Maduraprasa** [comment]
What is this

**Comment by 0983165121** [comment]
T

**Comment by LizzyOrji123** [comment]
The part i love most about your work is how beautifully crafted your meta tag section is.

**Comment by sa-ko4969** [comment]
> - [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
> 
> - [x] Have you explained what your changes do, and why they add value to the Guides?
> 
> 
> 
> **Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**
> 
> 
> 
> -----
> 
> 
> 
> I translated some part to Italian, but I wanted somebody else to check my progress, there are the folders and respective files for it = italian.
> 
> 
> 
> Regards
> 
>

**Review by Ptyrone489 — COMMENTED** [review]
###

**Review by Dossi1 — COMMENTED** [review]
Label for love octicon

**Review by yungeeng — COMMENTED** [review]
Every thing is confusing

**Comment by LizzyOrji123** [comment]
> Every thing is confusing

I would appreciate a more constructive feedback from you.
A project forked and contributed by a professional deserves a professional feedback from you. I am waiting for your constructive feedback stating the exact parts that are confusing to you.
Thank you.

**Comment by LizzyOrji123** [comment]
> Label for love octicon

Hi,
Could you be more detailed with what you wrote?

**Comment by ahpook** [comment]
@LizzyOrji123 these are just spam comments, don't worry about it - but thank you for replying. We get a lot of fake comments/prs on this project from accounts that are trying to boost reputation so they can be sold for more money.

**Comment by omarwbassam** [comment]
Ro

**Review by Rudyrude81 — COMMENTED** [review]
#3072

**Comment by Fahaddin24** [comment]
`main`

**Comment by Fahaddin24** [comment]
Support

**Review by Avalir1996 — COMMENTED** [review]
pipobarari:it

**Review by Ketchaiyo982 — COMMENTED** [review]
@

**Comment by m33and1990** [comment]
Imgsrc.ru

**Comment by m33and1990** [comment]
Www.yandex.ru

**Comment by JoseRuelas1990** [comment]
I can trasleite  to spanish
- [ ]

**Review by Hasmuni5757 — COMMENTED** [review]
Hurm

**Comment by BlueButterflies** [comment]
@pipobarari 
I can help you with the Italian tradition and finish the rest of the project to translate.  What do you say?
Ti posso aiutare nella tradizione in italiano e finire il resto dell progetto per tradure. Che ne dici?

**Review by Diamondb32 — COMMENTED** [review]
****

**Pull request closed without merging**
