### PR TITLE
Create datadog-synthetics.yml

### PR DESCRIPTION
**Pull request by Qoutip**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by Jaycubana** [comment]
565354

**Comment by Jaycubana** [comment]
@Jaycubana 3038

**Review by Kimj2539 — COMMENTED** [review]
Reviewed and changes made to #3038

**Comment by ahpook** [comment]
This is unnecessary and off topic

**Pull request closed without merging**
