### PR TITLE
Remove redundant period

### PR DESCRIPTION
**Pull request by WebSnke**
- [ x ] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [ x ] Have you explained what your changes do, and why they add value to the Guides?

Fixes the sentence which would otherwise end with ".:".

### CODE REVIEW

**Comment by Mbdrift** [comment]
hello, thank for this page!

**Comment by MikeMcQuaid** [comment]
Would rather keep this as-is, sorry!

**Comment by WebSnke** [comment]
<br>temp

<p align="center">Are you sure it is supposed to look like that?</p><br>

**Comment by MikeMcQuaid** [comment]
With more context: no, you're right, I'm sorry1

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @WebSnke!

**Comment by WebSnke** [comment]
> With more context: no, you're right, I'm sorry1

No problem.

**Comment by WebSnke** [comment]
The time on our comments seems to be wrong. I didn't write this 3 days ago.

**Review by lokalvandal — COMMENTED** [review]
``

**Comment by ijazork** [comment]
Hhyyyyy

**Comment by ijazork** [comment]
Hey

**Pull request merged**
