### PR TITLE
Modified Korean translation

### PR DESCRIPTION
**Pull request by JoonhunLee**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Review by danielski1988 — APPROVED** [review]

**Comment by JoonhunLee** [comment]
제가 오픈소스 가이드를 읽으면서 번역이 매끄럽지 않다고 느끼는 부분을 수정하고 있습니다.
I am correcting the translation that is not smooth while reading the open source guide.

혹시 의견이 있으신 분은 댓글 달아주시면 감사하겠습니다.
If you have any suggestions, please leave a comment.

**Comment by k2heart** [comment]
LGTM !

**Comment by JoonhunLee** [comment]
@itsbagpack 
I'm adjusting the schedule as the semester begins, so the revision is being delayed.
I won't change the title because I think I'll be working on it soon.
Thanks for comment! :)

**Review by itsbagpack — APPROVED** [review]

**Comment by itsbagpack** [comment]
@JoonhunLee thanks for your contribution. I'll merge the PR once the test builds are green.

**Comment by itsbagpack** [comment]
@JoonhunLee It looks like there are some test failures. If you could fix those, that will be great! We'll review the PR after.

**Review by Burkay5441 — APPROVED** [review]

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
Need to fix CI failures: https://github.com/github/opensource.guide/pull/2517/checks?check_run_id=3532345910#step:7:110

**Review by danielski1988 — APPROVED** [review]

**Review by MaryJaneLove4 — APPROVED** [review]
Ok

**Review by MaryJaneLove4 — APPROVED** [review]

**Comment by MaryJaneLove4** [comment]
👍

**Comment by MikeMcQuaid** [comment]
@JoonhunLee CI is still failing, sorry: https://github.com/github/opensource.guide/pull/2517/checks?check_run_id=3774401273#step:7:120

Do you need help understanding what needs to be done to fix this?

**Comment by JoonhunLee** [comment]
@MikeMcQuaid 
Oh I didn't have time for check this pr.. sorry
May I ask for help on this failure??

**Review by yanlinmin — COMMENTED** [review]
Sorry , I am using my phone is lost internet connection

**Pull request closed without merging**
