### PR TITLE
Convert in to Urdu language

### PR DESCRIPTION
**Pull request by Areebey**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by Lupobb** [comment]
In redmi/firebasa
Non ho la mail e relativa password
Quindi smettere di inviare mail x le dovute correzioni prendetevela con chi
ha creato il profilo
Venanzio Bianchi

Il mar 14 mag 2024, 07:43 Areeb Rafiq ***@***.***> ha scritto:

**Comment by jmeridth** [comment]
@Areebey Thank you for your contribution but it looks like you have a good number of errors to work through via the `GitHub Actions CI/tests` status check.

**Comment by Izaquel2024** [comment]
###

**Comment by 8012145393085** [comment]
Hello world

**Comment by ahpook** [comment]
@Areebey in order for this translation to work, you will need to add a YAML file as 
`_data/locales/ur.yml`  that follows the correct format - see https://github.com/github/opensource.guide/blob/main/_data/locales/en.yml  for the example.  

This will fix a lot of the test failures but there are many additional problems in the translation that must be fixed before this can merge. From the output of the test failures, I see some small changes that will fix most of the failures:

* any time there is an internal link in markdown to another page, like `building-community.md:29` :  

```
[A friendly README](../starting-a-project/#writing-a-readme)
```
The anchor after the `#` needs to link to the translated name of that header

* There are many links which have got Unicode characters embedded in them, maybe due to your editor? It looks like it has changed the ASCII `.` to a Unicode `&#1748` entity `۔ ` These need to be fixed for the links to work, example `building-community.md:179`

```
(https://github.com/rub inius/rubinius/blob/HEAD/.github/contributing۔ md):
```

Thank you for this work, I hope you will keep improving it so we can add this language!

**Comment by nickloo8888** [comment]
😂

**Comment by Bulls888** [comment]
Ok 3223

**Comment by Bulls888** [comment]
Oj

**Review by Wortason — COMMENTED** [review]
#–-

**Comment by Wortason** [comment]
[]
> #–-

**Review by Deasy89-malik — COMMENTED** [review]
Dukung. Harga penurunan

**Comment by ethiclegacy** [comment]
> @Areebey in order for this translation to work, you will need to add a YAML file as 
> 
> `_data/locales/ur.yml`  that follows the correct format - see https://github.com/github/opensource.guide/blob/main/_data/locales/en.yml  for the example.  
> 
> 
> 
> This will fix a lot of the test failures but there are many additional problems in the translation that must be fixed before this can merge. From the output of the test failures, I see some small changes that will fix most of the failures:
> 
> 
> 
> * any time there is an internal link in markdown to another page, like `building-community.md:29` :  
> 
> 
> 
> ```
> 
> [A friendly README](../starting-a-project/#writing-a-readme)
> 
> ```
> 
> The anchor after the `#` needs to link to the translated name of that header
> 
> 
> 
> * There are many links which have got Unicode characters embedded in them, maybe due to your editor? It looks like it has changed the ASCII `.` to a Unicode `&#1748` entity `۔ ` These need to be fixed for the links to work, example `building-community.md:179`
> 
> 
> 
> ```
> 
> (https://github.com/rub inius/rubinius/blob/HEAD/.github/contributing۔ md):
> 
> ```
> 
> 
> 
> Thank you for this work, I hope you will keep improving it so we can add this language! 

Contribute [](https://community.dynamics.com/crm)

**Review by ethiclegacy — COMMENTED** [review]
Formation changes

**Comment by nickloo8888** [comment]
什么叫跟踪拉取请求？本人有答应让你跟吗？？？

**Comment by nickloo8888** [comment]
> - [checked] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
> - [checked] Have you explained what your changes do, and why they add value to the Guides?
> 
> **Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**
> 
> ----- Lebih Punya pasal.
>

**Comment by nickloo8888** [comment]
Complate: Process completed with exit code 1. Well done.very good good job.you are the best .get full bonus.

**Comment by nickloo8888** [comment]
可以删除吗？和我没有关系的不要连过来。本人不明白是什么。 你不删除。我为你删除我本人账号

**Comment by ahpook** [comment]
@Areebey This is getting a lot of spam. I am going to lock conversation on this PR but will keep watching it for updates - if you push more commits I will re-open and hope we can get it merged. Thank you!

**Comment by jmeridth** [comment]
@Areebey Are you able to address the failing tests?

**Comment by jmeridth** [comment]
@Areebey going to close this.  Please reopen and update if you would like to.

**Pull request closed without merging**
