### PR TITLE
Fixed a small typo in the spelling of two

### PR DESCRIPTION
**Pull request by FanciestW**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/gh-pages/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by pg1992** [comment]
I thought the original text was correct, wasn't it? I think **to** is being used here as a _preposition_, not as a numeral, like:

> We went **to** Prague last year.
> I asked someone the way **to** the town centre.
> Link **to** duplicate issues, ...

Reference: [Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/to)

**Comment by FanciestW** [comment]
Both 'to' and 'two' work but will mean two different things. I depends on what the sentence is trying to state. It could either be stating that, "you create a link to a duplicate issue from an issue" or "you can link two issues that are duplicates". When I was reading, it sounded like it was saying, "you could link two duplicate issues". However, I can see how it can also be linking an issue to a duplicate. In which case, my correction is incorrect.

**Comment by lee-dohm** [comment]
Thanks for the contribution. I believe that the original text is in line with @nayafia's intent. I'll let her reopen this if my understanding is incorrect though :grinning:

Thanks again for helping out :+1:

**Comment by mlinksva** [comment]
FWIW I think 'link' is just a confusing word here. https://help.github.com/articles/about-duplicate-issues-and-pull-requests/ uses 'mark'.

Howabout

```
Mark [duplicate issues](https://help.github.com/articles/about-duplicate-issues-and-pull-requests/), and suggest new issue labels, to keep things organized
```

**Pull request closed without merging**
