### PR TITLE
add Italian translation

### PR DESCRIPTION
**Pull request by BlueButterflies**
Hi, I also added the Italian translation.
I would be happy for you to add this contribution of mine too

I changed the link between lines 101 and 115 for the text Broadening Node.js Contributions in each legal.md file because it doesn't exist

https://www.joyent.com/blog/broadening-node-js-contributions DOESN'T EXIST
https://www.tritondatacenter.com/blog/broadening-node-js-contributions EXIST

As you can see, the company "joyent.com" has moved its blog to another website "tritondatacenter.com"

And correct translation error in the folder "bg".

Thank you in advance

### CODE REVIEW

**Comment by BlueButterflies** [comment]
I changed the link between lines 101 and 115 for the text Broadening Node.js Contributions in each legal.md file because it doesn't exist

https://www.joyent.com/blog/broadening-node-js-contributions  **DOESN'T EXIST**
https://www.tritondatacenter.com/blog/broadening-node-js-contributions  **EXIST**

As you can see, the company **"joyent.com"** has moved its blog to another website **"tritondatacenter.com"**

**Review by 56494365 — COMMENTED** [review]
content/organizations/managing-programmatic-access-to-your-organization

**Review by 56494365 — COMMENTED** [review]
.

**Review by jmeridth — APPROVED** [review]
Thank you for your contribution.  Keep them coming @BlueButterflies.  And thank you for fixing the link in legal in each translation.

**Pull request merged**
