### PR TITLE
Circleci project setup

### PR DESCRIPTION
**Pull request by Alexalucky**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Review by ladygem — COMMENTED** [review]
Getting started

**Comment by Lbombo6969** [comment]
love this im in

**Comment by Burna7** [comment]
Your welcome.

**Comment by Rachi26** [comment]
Hay

**Comment by Burna7** [comment]
Yeah
How can we help you?

**Pull request closed without merging**
