### PR TITLE
changed some sentences

### PR DESCRIPTION
**Pull request by Teja-07**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by Teja-07** [comment]
I changed few lines in the paragraph  as this was my first pull request

**Review by Fii02kong — COMMENTED** [review]
#

**Comment by skaillet91** [comment]
https://github.com/github/opensource.guide/pull/2666#issue-1077473243

**Comment by nholden** [comment]
👋  Hi, @Teja-07! Thanks for this contribution. It's tough for me to see how this change adds value to the Guides, so I'm going to close it.

**Pull request closed without merging**
